import { GeneratorOptions } from '../types';

export function generatePlaywrightConfig(opts: GeneratorOptions): string {
  return `import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: 1,
  reporter: [['html'], ['list']],

  use: {
    baseURL: process.env.BASE_URL ?? '${opts.baseUrl}',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    headless: true,
  },

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
});
`;
}

export function generatePackageJson(opts: GeneratorOptions): string {
  return JSON.stringify({
    name: 'playwright-tests',
    version: '1.0.0',
    description: 'Playwright E2E tests — auto-generated by pw-generator',
    scripts: {
      test: 'playwright test',
      'test:ui': 'playwright test --ui',
      'test:headed': 'playwright test --headed',
      'test:report': 'playwright show-report',
    },
    devDependencies: {
      '@playwright/test': '^1.44.0',
      typescript: '^5.4.0',
      '@types/node': '^20.0.0',
    },
  }, null, 2);
}

export function generateTsConfig(): string {
  return JSON.stringify({
    compilerOptions: {
      target: 'ES2020',
      module: 'commonjs',
      lib: ['ES2020'],
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      outDir: './dist',
      baseUrl: '.',
      paths: {},
    },
    include: ['**/*.ts'],
    exclude: ['node_modules', 'dist'],
  }, null, 2);
}

// ─── Gitea Workflow Generator ─────────────────────────────────────
// Mirrors the working workflow from the existing playwright repo.
// upload-artifact is intentionally omitted — it relies on
// ACTIONS_RUNTIME_URL which Gitea sets to localhost:3000,
// unreachable from inside a container job. No workaround for this
// env var override works reliably on self-hosted Gitea.
//
// Report is instead saved to a named Docker volume (playwright-report)
// so it persists across runs and can be accessed from the host.

export function generateGiteaWorkflow(opts: GeneratorOptions): string {
  const { gitea } = opts;

  const lines = [
    `name: Playwright`,
    ``,
    `on:`,
    `  workflow_dispatch:`,
    `  push:`,
    `    branches:`,
    `      - ${gitea.branch}`,
    ``,
    `jobs:`,
    `  playwright:`,
    `    runs-on: ubuntu-latest`,
    `    container:`,
    `      image: ${gitea.playwrightImage}`,
    `      options: --add-host gitea:host-gateway --add-host host.docker.internal:host-gateway --mount type=volume,source=${gitea.npmCacheVolume},target=/root/.npm --mount type=volume,source=${gitea.reportVolume},target=/playwright-report`,
    `    env:`,
    `      APP_URL: http://${gitea.appHost}`,
    `      BASE_URL: http://${gitea.appHost}`,
    `    steps:`,
    `      - name: Checkout repository`,
    `        uses: actions/checkout@v4`,
    `        with:`,
    `          github-server-url: ${gitea.serverUrl}`,
    ``,
    `      - name: Install dependencies`,
    `        run: npm ci --prefer-offline --no-audit`,
    ``,
    `      - name: Run Playwright tests`,
    `        run: npx playwright test`,
    ``,
    `      - name: Save report to volume`,
    `        if: always()`,
    `        run: cp -r playwright-report/. /playwright-report/`,
  ];

  return lines.join('\n') + '\n';
}
