import { GeneratorOptions } from '../types';

export function generatePlaywrightConfig(opts: GeneratorOptions): string {
  return `import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: 1,
  reporter: [['html'], ['list']],

  use: {
    baseURL: process.env.BASE_URL ?? '${opts.baseUrl}',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    headless: true,
  },

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
});
`;
}

export function generatePackageJson(opts: GeneratorOptions): string {
  return JSON.stringify({
    name: 'playwright-tests',
    version: '1.0.0',
    description: 'Playwright E2E tests — auto-generated by pw-generator',
    scripts: {
      test: 'playwright test',
      'test:ui': 'playwright test --ui',
      'test:headed': 'playwright test --headed',
      'test:report': 'playwright show-report',
    },
    devDependencies: {
      '@playwright/test': '^1.44.0',
      typescript: '^5.4.0',
      '@types/node': '^20.0.0',
    },
  }, null, 2);
}

export function generateTsConfig(): string {
  return JSON.stringify({
    compilerOptions: {
      target: 'ES2020',
      module: 'commonjs',
      lib: ['ES2020'],
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      baseUrl: '.',
      paths: {},
    },
    include: ['**/*.ts'],
    exclude: ['node_modules'],
  }, null, 2);
}
